# Generated by Nompose
# Service: api
# Image: pay-api

job "api" {
  datacenters = ["dc1"]
  type        = "service"

  group "api" {
    count = 1

    network {
      port "http" {
        static = 3000
      }
    }

    task "app" {
      driver = "docker"

      config {
        image = "pay-api"
        ports = ["http"]
      }

      resources {
        cpu    = 500
        memory = 512
      }

      env {
        DATABASE_URL = "postgres://user:pass@db:5432/myapp"
        REDIS_URL = "redis://cache:6379"
      }

      service {
        name = "api"
        port = "http"
        tags = ["docker", "api"]

        check {
          type     = "http"
          path     = "/api/health"
          interval = "30s"
          timeout  = "3s"
          port     = "http"
        }
      }

      # Service dependencies detected:
      # Depends on: db
      # Depends on: cache
      # Note: Ensure dependent services are deployed first

    }
  }
}