# Generated by Nompose
# Service: cache
# Image: redis:alpine

job "cache" {
  datacenters = ["dc1"]
  type        = "service"

  group "cache" {
    count = 1

    network {
      port "http" {
        static = 6379
      }
    }

    task "app" {
      driver = "docker"

      config {
        image = "redis:alpine"
        ports = ["http"]
      }

      resources {
        cpu    = 500
        memory = 512
      }

      service {
        name = "cache"
        port = "http"
        tags = ["docker", "cache"]

      }

    }
  }
}