# Generated by Nompose
# Service: db
# Image: postgres:13

job "db" {
  datacenters = ["dc1"]
  type        = "service"

  group "db" {
    count = 1

    network {
      port "http" {
        static = 5432
      }
    }

    task "app" {
      driver = "docker"

      config {
        image = "postgres:13"
        ports = ["http"]
      }

      resources {
        cpu    = 500
        memory = 512
      }

      env {
        POSTGRES_DB = "myapp"
        POSTGRES_USER = "user"
        POSTGRES_PASSWORD = "pass"
      }

      service {
        name = "db"
        port = "http"
        tags = ["docker", "db"]

      }

      # Volumes detected - manual configuration may be needed:
      # postgres_data:/var/lib/postgresql/data


    }
  }
}