# Generated by Nompose
# Service: web
# Image: nginx:alpine

job "web" {
  datacenters = ["dc1"]
  type        = "service"

  group "web" {
    count = 3

    network {
      port "http" {
        static = 8080
      }
    }

    task "app" {
      driver = "docker"

      config {
        image = "nginx:alpine"
        ports = ["http"]
      }

      resources {
        cpu    = 500
        memory = 512
      }

      env {
        NGINX_HOST = "localhost"
        NGINX_PORT = "80"
      }

      service {
        name = "web"
        port = "http"
        tags = ["docker", "web"]

        check {
          type     = "http"
          path     = "/health"
          interval = "30s"
          timeout  = "3s"
          port     = "http"
        }
      }

      # Service dependencies detected:
      # Depends on: api
      # Note: Ensure dependent services are deployed first

    }
  }
}